//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Happy_New_Year
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Gift.
    /// </summary>
    // *** Start programmer edit section *** (Gift CustomAttributes)

    // *** End programmer edit section *** (Gift CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("GiftE", new string[] {
            "Date as \'Date\'",
            "Name as \'Name\'",
            "GiftType as \'Gift type\'",
            "GiftType.Name as \'Name\'"}, Hidden=new string[] {
            "GiftType.Name"})]
    [MasterViewDefineAttribute("GiftE", "GiftType", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("GiftL", new string[] {
            "Date as \'Date\'",
            "Name as \'Name\'",
            "GiftType.Name as \'Name\'"})]
    public class Gift : ICSSoft.STORMNET.DataObject
    {

        private System.DateTime fDate = System.DateTime.Parse("now");

        private string fName;

        private IIS.Happy_New_Year.GiftType fGiftType;

        // *** Start programmer edit section *** (Gift CustomMembers)

        // *** End programmer edit section *** (Gift CustomMembers)


        /// <summary>
        /// Date.
        /// </summary>
        // *** Start programmer edit section *** (Gift.Date CustomAttributes)

        // *** End programmer edit section *** (Gift.Date CustomAttributes)
        public virtual System.DateTime Date
        {
            get
            {
                // *** Start programmer edit section *** (Gift.Date Get start)

                // *** End programmer edit section *** (Gift.Date Get start)
                System.DateTime result = this.fDate;
                // *** Start programmer edit section *** (Gift.Date Get end)

                // *** End programmer edit section *** (Gift.Date Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Gift.Date Set start)

                // *** End programmer edit section *** (Gift.Date Set start)
                this.fDate = value;
                // *** Start programmer edit section *** (Gift.Date Set end)

                // *** End programmer edit section *** (Gift.Date Set end)
            }
        }

        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Gift.Name CustomAttributes)

        // *** End programmer edit section *** (Gift.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Gift.Name Get start)

                // *** End programmer edit section *** (Gift.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Gift.Name Get end)

                // *** End programmer edit section *** (Gift.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Gift.Name Set start)

                // *** End programmer edit section *** (Gift.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Gift.Name Set end)

                // *** End programmer edit section *** (Gift.Name Set end)
            }
        }

        /// <summary>
        /// Gift.
        /// </summary>
        // *** Start programmer edit section *** (Gift.GiftType CustomAttributes)

        // *** End programmer edit section *** (Gift.GiftType CustomAttributes)
        [PropertyStorage(new string[] {
                "GiftType"})]
        public virtual IIS.Happy_New_Year.GiftType GiftType
        {
            get
            {
                // *** Start programmer edit section *** (Gift.GiftType Get start)

                // *** End programmer edit section *** (Gift.GiftType Get start)
                IIS.Happy_New_Year.GiftType result = this.fGiftType;
                // *** Start programmer edit section *** (Gift.GiftType Get end)

                // *** End programmer edit section *** (Gift.GiftType Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Gift.GiftType Set start)

                // *** End programmer edit section *** (Gift.GiftType Set start)
                this.fGiftType = value;
                // *** Start programmer edit section *** (Gift.GiftType Set end)

                // *** End programmer edit section *** (Gift.GiftType Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "GiftE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View GiftE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("GiftE", typeof(IIS.Happy_New_Year.Gift));
                }
            }

            /// <summary>
            /// "GiftL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View GiftL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("GiftL", typeof(IIS.Happy_New_Year.Gift));
                }
            }
        }
    }
}

