//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Happy_New_Year
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Gift type.
    /// </summary>
    // *** Start programmer edit section *** (GiftType CustomAttributes)

    // *** End programmer edit section *** (GiftType CustomAttributes)
    [AutoAltered()]
    [Caption("Gift type")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("GiftTypeE", new string[] {
            "Name as \'Name\'"})]
    [View("GiftTypeL", new string[] {
            "Name as \'Name\'"})]
    public class GiftType : ICSSoft.STORMNET.DataObject
    {

        private string fName;

        // *** Start programmer edit section *** (GiftType CustomMembers)

        // *** End programmer edit section *** (GiftType CustomMembers)


        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (GiftType.Name CustomAttributes)

        // *** End programmer edit section *** (GiftType.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (GiftType.Name Get start)

                // *** End programmer edit section *** (GiftType.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (GiftType.Name Get end)

                // *** End programmer edit section *** (GiftType.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (GiftType.Name Set start)

                // *** End programmer edit section *** (GiftType.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (GiftType.Name Set end)

                // *** End programmer edit section *** (GiftType.Name Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "GiftTypeE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View GiftTypeE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("GiftTypeE", typeof(IIS.Happy_New_Year.GiftType));
                }
            }

            /// <summary>
            /// "GiftTypeL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View GiftTypeL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("GiftTypeL", typeof(IIS.Happy_New_Year.GiftType));
                }
            }
        }
    }
}

